# Generated by Django 3.0.5 on 2021-06-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210615_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('U', 'user'), ('M', 'moderator'), ('A', 'admin')], default='U', max_length=1, verbose_name='Уровень пользователя'),
        ),
    ]
